# Generated by Django 3.2.15 on 2024-06-09 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisOrganization',
            fields=[
                ('Name', models.CharField(max_length=50, verbose_name='机构名字')),
                ('Address', models.CharField(max_length=100, verbose_name='机构地址')),
                ('Phone', models.CharField(max_length=20, verbose_name='机构电话')),
                ('AnalysisID', models.AutoField(primary_key=True, serialize=False, verbose_name='分析机构ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('PortID', models.AutoField(primary_key=True, serialize=False, verbose_name='港口ID')),
                ('Name', models.CharField(max_length=50, verbose_name='港口的名称')),
                ('Location', models.CharField(max_length=100, verbose_name='位置')),
                ('Type', models.CharField(max_length=30, verbose_name='港口的类型')),
                ('Capacity', models.IntegerField(verbose_name='港口的容量')),
            ],
        ),
        migrations.CreateModel(
            name='Regulatory',
            fields=[
                ('Name', models.CharField(max_length=50, verbose_name='机构名字')),
                ('Address', models.CharField(max_length=100, verbose_name='机构地址')),
                ('Phone', models.CharField(max_length=20, verbose_name='机构电话')),
                ('RegulatoryID', models.AutoField(primary_key=True, serialize=False, verbose_name='监管局ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ship_type', models.CharField(max_length=50)),
                ('capacity', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('draft', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShipCrew',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ShipID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OAuth.ship')),
            ],
        ),
        migrations.CreateModel(
            name='DataAnalyst',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('AppointerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OAuth.analysisorganization')),
            ],
        ),
    ]
